### ISSUE TITLE
It seems that "Localized material name" doesn't work

### ISSUE THREAD

**Issue by Clexus** [Xezard/XItemsRemover#8]
I use Chinsese but the drop item will still display English

**Comment by Xezard** [comment]
What server core are you using? And on which version? What does your config look like, can you paste it here, or send a screenshot?

**Comment by Clexus** [comment]
> What server core are you using? And on which version? What does your config look like, can you paste it here, or send a screenshot?

Paper, the lastest 1.12.2 version
config:
```
Items:
  # available placeholders
  # {time} - time remaining before remove (in seconds)
  # {display_name} - display name of itemstack (if empty - used localized material name}
  # {amount} - itemstack amount
  Display-name-format: "§c⚠ {time} §7| §f{display_name} §a{amount}x"
  Remove-timer:
    # Timer for removing an item in seconds
    Default: 30
    After-player-death: 180
    Async: true
    # Section for specifying a unique timer or display name
    # for certain materials
    # Format:
    # <material name>:
    #   <timer>: 15
    #   <display name>: "Test"
    # If you only need to edit one parameter
    # (name or time) you can just delete the line with the second.
    Custom-materials:
      COBBLESTONE:
        Timer: 15
        Display-name: "Cobblestone :D"
      STONE:
        Timer: 10
      GRASS:
        Display-name: "Grazz"
```
